module_name: CRON Jobs
compatible_versions: 1.0.0+
author: thirty bees
category: administration
tags:
  - cron
  - cron job
  - authomatic run
  - cronjobs
description_short: The CRON jobs module allows for you to run some tasks automatically in your shop.
description: description.md
images:
  - image-1.png
license: AFL